### ISSUE TITLE
Testing with jest

### ISSUE THREAD

**Issue by anibal-deboni-gaivota** [zhujun24/http-request-context#4]
When I run my tests with jest three of them returns:
`Jest has detected the following 3 open handles potentially keeping Jest from exiting`

Pointing this part of the code:
```
       28 |       .use(express.json({ limit: '100mb' }))
       29 |       .use(express.urlencoded({ limit: '100mb', extended: true }))
       30 |       .use(httpContext.middleware({
          |                        ^
      31 |         removeAfterClose: true,
      32 |         removeAfterFinish: true,
      33 |       }))

      at interval (node_modules/http-request-context/index.js:22:3)
      at Object.middleware (node_modules/http-request-context/index.js:119:5)
      at new WebApp (src/infra/web/index.ts:30:24)
```

Any ideia what am I doing wrong? Already tried to move the middleware to other parts of the express instantiation but the problem remains.

**Comment by zhujun24** [comment]
@anibal-deboni-gaivota I have not reproduced this issue, please provide a minimal example, or try https://stackoverflow.com/questions/50818367/how-to-fix-err-jest-has-detected-the-following-3-open-handles-potentially-keepin
